config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :invitations, only: [:new, :create]
  get 'payments', to: 'payments#index'
  get 'chat', to: 'home#index'

  devise_scope :user do
    get 'signout', to: 'users/sessions#destroy'
    get 'users/sign_up/:invited_code', to: 'users/registrations#new', as: :new_registration

    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
      get 'calendar', to: 'dashboard#calendar'
      get 'users/autocomplete', to: 'users#autocomplete', as: 'autocomplete_users'
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end

    post 'tokens' => "tokens#create"
  end

  namespace :admin do
    root 'dashboard#index'
    resources :users do
      patch 'pay_for_event', on: :member
    end

    resources :invitations, except: [:update]
    patch 'invitations/:id', to: 'invitations#resend', as: 'invitation_resend'
    patch 'invitation/:id', to: 'invitations#approve_user', as: 'approve'

    resources :events

    resources :payments, only: [:index]
    resources :rates, only: [:edit, :update]
    resources :items, only: [:new, :create]
  end

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" }

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_filter :admin_only
  
  def index
    @events = Event.where("date IS NOT NULL")
    @custom_events = Event.where("date IS NULL")
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @events = current_user.events.limit(10)
    @my_events = current_user.created_events.limit(10)
  end

  def calendar
    @custom_events = current_user.events.where("date IS NULL")
    @events = current_user.events.where("date IS NOT NULL")
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
  end

protected

    def sortable_columns
      super.push("name", "paid_type", "date")
    end 
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/calendar.html.haml
.row
  = render 'shared/user_bar'
.row
  = render 'shared/calendar'
  = render 'shared/event_without_date_table'

app/views/dashboard/index.html.haml
.row
  = render 'shared/user_bar'
.row
  - if @events.present?
    .col-lg-6
      .hpanel
        .panel-heading
          .panel-tools
            =link_to "#", class: "showhide" do
              %i{ class: "glyphicon glyphicon-chevron-up"}
          Events
        .panel-body
          = render 'shared/event_table', events: @events
        .panel-footer.right-align
          =link_to 'View all events', events_path(user_id: current_user.id), class: "btn"
  - if @my_events.present?
    .col-lg-6
      .hpanel
        .panel-heading
          .panel-tools
            =link_to "#", class: "showhide" do
              %i{ class: "glyphicon glyphicon-chevron-up"}
          My events
        .panel-body
          = render 'shared/event_table', events: @my_events
        .panel-footer.right-align
          =link_to 'View all my events', events_path, class: "btn"