config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :invitations, only: [:new, :create]
  get 'payments', to: 'payments#index'
  get 'chat', to: 'home#index'

  devise_scope :user do
    get 'signout', to: 'users/sessions#destroy'
    get 'users/sign_up/:invited_code', to: 'users/registrations#new', as: :new_registration

    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
      get 'calendar', to: 'dashboard#calendar'
      get 'users/autocomplete', to: 'users#autocomplete', as: 'autocomplete_users'
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end

    post 'tokens' => "tokens#create"
  end

  namespace :admin do
    root 'dashboard#index'
    resources :users do
      patch 'pay_for_event', on: :member
    end

    resources :invitations, except: [:update]
    patch 'invitations/:id', to: 'invitations#resend', as: 'invitation_resend'
    patch 'invitation/:id', to: 'invitations#approve_user', as: 'approve'

    resources :events

    resources :payments, only: [:index]
    resources :rates, only: [:edit, :update]
    resources :items, only: [:new, :create]
  end

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" }

end

app/views/admin/_admin_bar.html.haml
.row.bar-margin
  .col-lg-12
    %ul.nav.nav-tabs
      %li{ :class => "#{'active' if current_page?(admin_root_path)}" }
        = link_to 'Dashboard', admin_root_path
      %li{ :class => "#{'active' if current_page?(admin_users_path)}" }
        = link_to 'Users', admin_users_path
      %li{ :class => "#{'active' if current_page?(admin_invitations_path)}" }
        = link_to 'Invitations', admin_invitations_path
      %li{ :class => "#{'active' if current_page?(admin_events_path)}" }
        = link_to 'Events', admin_events_path
      =link_to "New event", new_event_path, class: "btn btn-primary pull-right"
      = render file: '/admin/invitations/new'