config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :invitations, only: [:new, :create]
  get 'payments', to: 'payments#index'
  get 'chat', to: 'home#index'

  devise_scope :user do
    get 'signout', to: 'users/sessions#destroy'
    get 'users/sign_up/:invited_code', to: 'users/registrations#new', as: :new_registration

    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
      get 'calendar', to: 'dashboard#calendar'
      get 'users/autocomplete', to: 'users#autocomplete', as: 'autocomplete_users'
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end

    post 'tokens' => "tokens#create"
  end

  namespace :admin do
    root 'dashboard#index'
    resources :users do
      patch 'pay_for_event', on: :member
    end

    resources :invitations, except: [:update]
    patch 'invitations/:id', to: 'invitations#resend', as: 'invitation_resend'
    patch 'invitation/:id', to: 'invitations#approve_user', as: 'approve'

    resources :events

    resources :payments, only: [:index]
    resources :rates, only: [:edit, :update]
    resources :items, only: [:new, :create]
  end

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" }

end

app/views/shared/_calendar.html.haml
.col-lg-10
  .hpanel
    .panel-body
      #calendar
        %h2#month
          = link_to "<", :month => l(@date.beginning_of_month - 1)
          = h @date.strftime("%B %Y")
          = link_to ">", :month => l(@date.end_of_month + 1)
        = calendar_for @events, :year => @date.year, :month => @date.month do |calendar|
          = calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')
          = calendar.day(:day_method => :date) do |date, events|
            .new-event-hide-button.hidden
              =link_to "+", new_event_path(date: date), toggle: "tooltip", title: 'New event', class: "btn btn-primary"
            = date.day
            %ul
              - events.each do |event|
                %li{ toggle: "tooltip", title: ("Paid event" if event.paid? || event.custom?), class: "#{event.paid_type}-event" }
                  %i{ class: ("glyphicon glyphicon-piggy-bank" if event.paid? || event.custom?) }
                  - if current_user.admin?
                    = link_to h(event.name), admin_event_path(event, format: :js), remote: true
                  - else
                    = link_to h(event.name), event_path(event, format: :js), remote: true
                  

app/views/shared/_event_amount.html.haml
.hpanel#income-outcome
  .panel-body.text-center.h-200
    %i.glyphicon.glyphicon-piggy-bank.gi-3x
    %h1.m-xs= @event.amount
    %h3.font-extra-bold.no-margins.text-success
      All Income
    %small This event has no fixed amount. You can pay as much as you wish.
  .panel-footer
    =link_to 'Take off', new_admin_item_path(@event, event_id: @event.id), remote: true, class: "btn btn-success"
    %span.pull-right
      %span All Outcome
      %h5= number_to_currency(@event.credit_items.sum(:amount), unit: "₴", format: "-%n %u")

app/views/shared/_event_form.html.haml
.hpanel.col-lg-6.col-lg-offset-3
  .panel-body
    .form.form-group
      = simple_form_for @event, method: method do |f|
        = f.input :name, required: true, placeholder: "Name", class: 'form-control'
        = f.input :description, required: true, placeholder: "Few words about event"
        .hr-line-dashed
        = f.input :paid_type, as: :radio_buttons, collection: ['free', 'paid', 'custom'], item_wrapper_class: 'radio-inline', label_html: { class: "radio-inline"}
        %div#disabled_for_free
          = f.input :calculate_amount, label_html: { class: "pull-right"}
          = f.input :amount, required: true, disabled: @event.calculate_amount?
          .hr-line-dashed
        = f.association :celebrators, label_method: :full_name, value_method: :id, include_blank: false
        .hr-line-dashed
        = f.input :date, label: false, wrapper: :datepicker do 
          %span.input-group-addon
            %i.glyphicon.glyphicon-calendar
          = f.input_field :date, as: :string, class: 'form-control input-datepicker'
        .hr-line-dashed
        = f.input :add_all_users, label_html: { class: "pull-right"}
        .form-group
          = text_field_tag nil, nil, data: { autocomplete: autocomplete_users_path(format: :json) }, class: "form-control", id: "event_participant_autocomplete"
          %br
          .row
            #participant-field
              - if @event.participants.any?
                - @event.participants.each do |participant|
                  = f.simple_fields_for :participant do |ff|
                    .col-lg-6
                      %fieldset.form-control
                        = ff.label :full_name, label: "#{participant.full_name}", required: false
                        = ff.hidden_field :_destroy, name: 'event[participant_ids][]', value: participant.id
                        %span.remove_fields.close &times;
        .hr-line-dashed          
        = f.button :submit, 'Save', class: "btn-primary"
        =link_to 'Back', :back, class: "btn btn-default pull-right"

app/views/shared/_event_payments_history.html.haml
.hpanel
  .panel-heading
    .panel-tools
      =link_to "#", class: "showhide" do
        %i{ class: "glyphicon glyphicon-chevron-up" }
    Payments history
  .panel-body
    %table.table#event-show-participants
      %thead
        %th Full name
        %th Date
        %th.text-right Paid
      %tbody
        - @items.each do |item|
          %tbody
            %tr
              - if item.payment.present?
                %td= item.payment.participant.full_name
                %td= item.created_at.strftime("%d.%m.%Y at %T")
                %td.text-right= number_to_currency(item.amount, unit: "₴", format: "%n %u")
              - else
                %td= item.created_by.full_name
                %td= item.created_at.strftime("%d.%m.%Y at %T")
                %td.text-right= number_to_currency(item.amount, unit: "₴", format: "-%n %u")
    = will_paginate @items

app/views/shared/_event_show.html.haml
.hpanel.hgreen
  .panel-body
    %h3= @event.name
    %b Description
    %p= @event.description
    %p
      -if @event.date.present?
        %b Date
        %span= @event.date.strftime('%d.%m.%Y')
    - if @event.celebrators.any?
      %p
        %b Celebrators
        %span= @event.celebrators.map(&:full_name).join(", ")
    %p
      %b Members
      %span= @event.participants.map(&:full_name).join(", ")

app/views/shared/_event_show_modal.html.haml
.modal.fade{id: dom_id(@event, :modal), "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h4.modal-title= @event.name
      .modal-body
        = render 'shared/event_show'
      .modal-footer
        - if current_user.admin? 
          =link_to "View more details", admin_event_path(@event), class: "btn btn-primary"
        - else
          =link_to "View more details", event_path(@event), class: "btn btn-primary"
        =link_to "Close", "#", "data-dismiss" => "modal", class: "btn btn-default"

app/views/shared/_event_table.html.haml
%table.table
  %thead
    %tr
      %th=sort_link "name", "Event"
      %th=sort_link "date"
      %th=sort_link "paid_type"
      - if current_user.admin?
        %th Creator
        %th Celebrators
      %th.text-right Actions
  %tbody
    - events.each do |event|
      %tr
        %td
          - if current_user.admin?
            =link_to "#{event.name}", admin_event_path(event), toggle: "tooltip", title: "View event details"
          - else
            =link_to "#{event.name}", event_path(event), toggle: "tooltip", title: "View event details"
        %td= event.date.strftime('%d.%m.%Y') if event.date.present?
        %td= event.paid_type
        - if current_user.admin?
          %td= event.creator.full_name
          %td
            - event.celebrators.each do |celebrator|
              %p=celebrator.full_name
        %td.text-right.glyphicon-margin
          - if current_user.admin?
            =link_to '', admin_event_path(event), toggle: "tooltip", title: "View event details", class: "glyphicon glyphicon-eye-open"
            =link_to '', edit_admin_event_path(event), toggle: "tooltip", title: "Edit event", class: "glyphicon glyphicon-pencil"
            =link_to '', admin_event_path(event), method: :delete, toggle: "tooltip", title: "Delete event", class: "glyphicon glyphicon-trash"
          - else
            =link_to '', event_path(event), toggle: "tooltip", title: "View event details", class: "glyphicon glyphicon-eye-open"
            - if event.creator == current_user
              =link_to '', edit_event_path(event), toggle: "tooltip", title: "Edit event", class: "glyphicon glyphicon-pencil"
              =link_to '', event_path(event), method: :delete, toggle: "tooltip", title: "Delete event", class: "glyphicon glyphicon-trash"

app/views/shared/_event_without_date_table.html.haml
- if  @custom_events.any?
  .col-lg-2
    .hpanel#without-date
      .panel-heading
        .panel-tools
          =link_to "#", class: "showhide" do
            %i{ class: "glyphicon glyphicon-chevron-up"}
        Custom events
      .panel-body
        %table.table
          %tbody
            - @custom_events.each do |event|
              %tr
                %td
                  - if current_user.admin?
                    %dt=link_to h(event.name), admin_event_path(event), remote: true, toggle: "tooltip", title: "View event details"
                  - else
                    %dt=link_to h(event.name), event_path(event), remote: true, toggle: "tooltip", title: "View event details"
                  %dd.text-right=number_to_currency(event.amount, unit: "₴", format: "%n %u")

app/views/shared/_payment_progress_for_event.html.haml
.hpanel.stats#payments-progress
  .panel-body.h-200
    .stats-title.pull-left
      %h4 Payments activity
    .stats-icon.pull-right
      %i.glyphicon.glyphicon-piggy-bank.gi-3x
    .m-t-xl
      %h3.m-b-xs= @event.amount
      %span.font-bold.no-margins
        Event amount
      .progress.m-t-xs.full.progress-small
        .progress-bar.progress-bar-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{@event.paid_percent}", :role => "progressbar", :style => "width: #{@event.paid_percent}%"}
      .row
        .col-xs-6
          %small.stats-label Balance
          %h4= @event.balance_to_pay.round(2)
        .col-xs-6
          %small.stats-label % Paid
          %h4= "#{@event.paid_percent.round(2)}%"

app/views/shared/_user_bar.html.haml
.row.bar-margin
  .col-lg-12
    %ul.nav.nav-tabs
      %li{ :class => ('active' if current_page?(authenticated_root_path)) }
        = link_to 'Dashboard', authenticated_root_path
      %li{ :class => ('active' if current_page?(events_path)) }
        = link_to 'Events', events_path
      %li{ :class => ('active' if current_page?(payments_path)) }
        = link_to 'Payments', payments_path
      %li{ :class => ('active' if current_page?(calendar_path)) }
        = link_to 'Calendar', calendar_path
      %li.pull-right
        =button_to "New event", new_event_path, method: :get, class: "btn btn-primary"