config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :invitations, only: [:new, :create]
  get 'payments', to: 'payments#index'
  get 'chat', to: 'home#index'

  devise_scope :user do
    get 'signout', to: 'users/sessions#destroy'
    get 'users/sign_up/:invited_code', to: 'users/registrations#new', as: :new_registration

    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
      get 'calendar', to: 'dashboard#calendar'
      get 'users/autocomplete', to: 'users#autocomplete', as: 'autocomplete_users'
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end

    post 'tokens' => "tokens#create"
  end

  namespace :admin do
    root 'dashboard#index'
    resources :users do
      patch 'pay_for_event', on: :member
    end

    resources :invitations, except: [:update]
    patch 'invitations/:id', to: 'invitations#resend', as: 'invitation_resend'
    patch 'invitation/:id', to: 'invitations#approve_user', as: 'approve'

    resources :events

    resources :payments, only: [:index]
    resources :rates, only: [:edit, :update]
    resources :items, only: [:new, :create]
  end

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" }

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  scope :should_expire, -> { where("updated_at < ? AND approved = ?", (Time.now - 36.hours), true) }
  scope :should_delete, -> { where("updated_at < ? AND approved = ?", (Time.now - 2.days), true) }
 
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  
  def expired
    updated_at + 2.days
  end

  def will_expired?
    ((expired - 12.hours) < Time.now) && approved?
  end
end

app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < ApplicationController
  before_filter :admin_only
  before_action :invitation_params, only: [:create]
  def index
    @invitations = Invitation.order(order_query)
  end  

  def new
    @invitation = Invitation.new
  end

  def create
    if Invitation.where(email: invitation_params[:email]).present?
      flash[:danger] = "Invitation has already been sent"
      redirect_to :back
    else
      @invitation = Invitation.new(invitation_params)
      @invitation.invited_code = Devise.friendly_token(length = 30)
      @invitation.approved = true
      if @invitation.save
        UserMailer.invitation_email(@invitation).deliver_now
      end
      flash[:success] = "Invitation was successfully sent"
      redirect_to :back
    end
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    UserMailer.deleting_invitation_email(@invitation).deliver_now
    @invitation.destroy
    flash[:success] = 'Invitation deleted'
    redirect_to :back
  end

  def resend
    @invitation = Invitation.find(params[:id])
    if @invitation.update(updated_at: Time.now)
      UserMailer.invitation_email(@invitation).deliver_now
    end
    respond_to do |format|
      format.html
      format.js { flash[:success] = "Invitation was successfully sent" }
    end
  end

  def approve_user
    @invitation = Invitation.find(params[:id])
    if @invitation.update(approved: true, invited_code: Devise.friendly_token(length = 30))
      UserMailer.invitation_email(@invitation).deliver_now
    end
    flash[:success] = "Invitation was successfully sent"
    redirect_to :back
  end

  private

    def invitation_params
      params.require(:invitation).permit(:email)
    end

  protected

    def sortable_columns
      super.push("email", "updated_at")
    end 
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  skip_before_filter :authenticate_user!
  before_action :invitation_params, only: [:create]
  
  def new
    Invitation.new
  end

  def create
    if Invitation.where(email: invitation_params[:email]).any?
      flash[:danger] = "Request has already been sent"
      redirect_to unauthenticated_root_path
    else
      @invitation = Invitation.new(invitation_params)
      if @invitation.save
        flash[:success] = "Request was successfully sent"
        redirect_to unauthenticated_root_path
      else
        flash[:danger] = "Something went wrong. Try again, please."
        redirect_to :back
      end
    end
  end

  private

    def invitation_params
      params.require(:invitation).permit(:email)
    end
end

app/helpers/admin/invitations_helper.rb
module Admin::InvitationsHelper
end

app/views/admin/invitations/index.html.haml
.row
  = render 'admin/admin_bar'
.row
  .col-lg-12
    .hpanel
      .panel-heading
        .panel-tools
          =link_to "#", class: "showhide" do
            %i{ class: "glyphicon glyphicon-chevron-up"}
        Invitations
      .panel-body
        %table.table
          %thead
            %tr
              %th=sort_link "email"
              %th=sort_link "updated_at", "Expired"
              %th Status
              %th.text-right Actions
          %tbody
            - @invitations.each do |invitation|
              %tr{ class: "#{'expired' if invitation.will_expired? }"}
                %td= invitation.email
                %td= invitation.expired.localtime.strftime("%d.%m.%Y at %T") if invitation.approved?
                - unless invitation.approved?
                  %td=link_to '', admin_approve_path(invitation), method: :patch, toggle: "tooltip", title: "Approve user request to registration", class: "glyphicon glyphicon-ban-circle"
                - else
                  %td
                    %i.glyphicon.glyphicon-ok-circle
                %td.text-right.glyphicon-margin
                  =link_to '', admin_invitation_resend_path(invitation), method: :patch, remote: true, toggle: "tooltip", title: "Resend invitation", class: "glyphicon glyphicon-send" if invitation.approved?
                  =link_to '', admin_invitation_path(invitation), method: :delete, toggle: "tooltip", title: "Delete invitation", class: "glyphicon glyphicon-trash"

app/views/admin/invitations/new.html.haml
.row
  .container
    = simple_form_for :invitation, url: admin_invitations_path, method: :post do |f|
      .row
        .input-group.col-md-4.pull-right
          = f.input :email, :placeholder => "E-mail", label: false, class: 'form-control'
          .input-group-btn
            = f.submit 'Send invitation', name: nil, class: 'btn btn-default'

app/views/admin/invitations/resend.js.erb
$('#flash').html("<%=j flash_message %>");